name: florian_app
description: A women safety app with emergency features

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  geolocator: ^11.0.1
  url_launcher: ^6.2.2
  permission_handler: ^11.0.1
  flutter_local_notifications: ^16.3.0
  shared_preferences: ^2.2.2
  http: ^1.1.0
  google_maps_flutter: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  #assets:
   # - assets/images/
    #- assets/icons/